export { CourtMeshClient } from "./client.js";
export type { CourtMeshClientOptions, FetchLike } from "./client.js";

export {
  CourtMeshError,
  ValidationError,
  AuthenticationError,
  PermissionError,
  NotFoundError,
  RequestTimeoutError,
  RateLimitError,
  ServerError,
  BadGatewayError,
  ServiceUnavailableError,
  NetworkError,
  isCourtMeshError,
  mapStatusToError,
} from "./errors.js";
export type { CourtMeshErrorCode } from "./errors.js";

export type {
  StringOrArray,
  YearParam,
  ApiResponse,
  KeywordSearchPagination,
  SemanticSearchPagination,
  SearchJudgesOptions,
  SearchJudgesMeta,
  SearchCasesOptions,
  SearchCasesMeta,
  SearchCasesResponse,
  SearchHit,
  SemanticSearchFilters,
  SemanticSearchOptions,
  SemanticSearchMeta,
  SemanticSearchResponse,
  CaseListItem,
  CaseDetails,
  GetCaseMeta,
  CaseAnalysisIssue,
  CaseAnalysisCitedCases,
  CaseAnalysisArguments,
  CaseAnalysisData,
  CaseAnalysisNotAvailable,
  CaseAnalysisAvailable,
  CaseAnalysis,
  GetCaseAnalysisMeta,
  RelatedDocument,
  TimelineEventStatus,
  TimelineEvent,
  RelatedResponse,
  RelatedMeta,
  PdfResponse,
  GetPdfMeta,
  AnalyzeCaseOptions,
  AnalyzeCaseStarted,
  AnalyzeCaseAlreadyExists,
  AnalyzeCaseResult,
  AnalyzeCaseMeta,
  AnalyzeConsolidatedOptions,
  ConsolidatedAnalysisData,
  AnalyzeConsolidatedResult,
  AnalyzeConsolidatedMeta,
  TimelineJobStatus,
  OrderDocument,
  RequestTimelineResult,
  RequestTimelineMeta,
  TimelineJob,
  GetTimelineMeta,
  HealthResponse,
} from "./types.js";
